### ISSUE TITLE
Commit of large matrices

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit-examples#13]
Et allez encore la même boulette! J'ai mis a jour une ancienne version sauf que les cov y étaient... Et elles y sont restées lors du merge...
https://github.com/openspyrit/spyrit-examples/commit/f243b5efe855c7c8e80a36f281d110be37527e47
Désolé Thomas... On en parle après Fadoua ?

**Comment by tbaudier** [comment]
c'est ok

**Comment by nducros** [comment]
Génial, merci Thomas ! 
Je suis censé faire quoi avec ma version locale pour ne pas recommencer ? Je supprime et reclone ?

**Comment by tbaudier** [comment]
Oui c'est le plus simple si tu n'as rien de modifié. Sinon, pousse sur une branche
